# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d865d5c1e607724bcad347a9015d7de1a9106458acfadcfad28a6a7d0b7469398097029e75e5a0730d5b1f6d0be0d21ccf2e705f747ebff7f90c4430ecac961

test:
  secret_key_base: 3af62659e6367655d68c35f366acdef8a85e095027b1a70f09dc44409819becd962012615b14021323531590f75c9ea6ff6fa604df1a88721cb8b13ae9cbaaa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
